### ISSUE TITLE
Bytecode weaving temporarily broken in compile from source artemis-odb.

### ISSUE THREAD

**Issue by DaanVanYperen** [DaanVanYperen/libgdx-artemis-quickstart#11]
@junkdog said: bytecode weaving [in artemis-odb] is borked atm due to structural changes to BaseSystem classes, but the main artemis module is intact.
https://gitter.im/junkdog/artemis-odb

Workaround: Use repo 0.9.1-SNAPSHOT until it gets fixed.

**Comment by junkdog** [comment]
fixed in https://github.com/junkdog/artemis-odb/commit/f89a99a045a6c28a7d4d8b5c3f8a910b27510dcd

**Comment by DaanVanYperen** [comment]
@junkdog :cookie:
