### ISSUE TITLE
Update to ecs-matrix 0.2.0

### ISSUE THREAD

**Issue by voidburn** [DaanVanYperen/libgdx-artemis-quickstart#15]
The currently employed one (net.onedaybeard.ecs:matrix-cli:0.1.1) lacks the fixes recently applied to the html/css generation of the matrix (which breaks component labels in the matrix output) and does not compile if the sourceCompatibility of the project is set to 1.8 instead of 1.7.

Update with:
net.onedaybeard.ecs:matrix-cli:0.2.0

**Comment by DaanVanYperen** [comment]
Thanks for the report @voidburn!
