### ISSUE TITLE
Fluid Entity Imports not working

### ISSUE THREAD

**Issue by brettsaunders21** [DaanVanYperen/libgdx-artemis-quickstart#25]
I have cloned the project, imported into IntelliJ IDEA 2019.1.

The project syncs correctly, but the imports for fluid entity aren't working and show as can't resolve symbol?

`import com.artemis.E;`
`import com.artemis.FluidIteratingSystem;`

Java 1.8
I haven't changed anything in the project.

**Comment by DaanVanYperen** [comment]
The maven plugin generates the files you need. IntelliJ won't trigger the plugin by itself. Workaround is running maven compile on core module from the IntelliJ maven panel whenever you change component classes. IntellIJ should pick up the generated files immediately without having to reimport.

**Comment by brettsaunders21** [comment]
Thank you, all working now
