### ISSUE TITLE
can't build android

### ISSUE THREAD

**Issue by telostia** [DaanVanYperen/libgdx-artemis-quickstart#8]
desktop build works fine but can't build using androd. keeps getting errors as below:

```
 com.android.ide.common.internal.LoggedErrorException: Failed to run command:
       C:\android-sdk-windows\build-tools\22.0.1\dx.bat --dex --output C:\Users
telostia\git\quickstart\android\build\intermediates\pre-dexed\debug\gdx-backend
gwt-1.6.1-bfd96f96923cdbc31e94bf48379d11fe45f37735.jar C:\Users\telostia\.gradl
\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-backend-gwt\1.6.1\f9552a7
b470dd8c91fd14a4f21058d13133c8c4\gdx-backend-gwt-1.6.1.jar
rror Code:
       1
utput:

       trouble processing "java/io/BufferedInputStream.class":

       Ill-advised or mistaken usage of a core class (java.* or javax.*)
       when not building a core library.


-----------------------------------------------------------------------------------------------------
```

tried removing html project and it stil reports error about backend-gwt even when I'm building android using android:installdebug

**Comment by telostia** [comment]
it would seem that that the artemis-odb processor was causing this problem.
originally when first tried to build this project, the error it caused was that net.onedaybeard.artemis:artemis-odb-gradle-plugin:0.9.1-SNAPSHOT was not found the provided repositories. so i removed mavenLocal() and  added the following 

        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }

I would imagine the 0.9.1-snapshot that you have on your system is more stable perhaps? desktop and gwt works fine but only android does not run. have you tried building the android yourself?
cheers.
It would be very helpful if you could fix this problem as this project seems interesting that I want to build my game on it. In the meantime I'm just going to use the basic artemis odb 0.9.0 without weaving or contrib to get it going.

**Comment by DaanVanYperen** [comment]
Looks like one of the odb-contrib erroneously referenced gdx backend. Pushed out a new version of both, should be fixed now! Thanks for the report @telostia!
